default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: finally_development

test:
  <<: *default
  database: finally_test

staging:
  <<: *default
  database: finally_staging
  username: <%= Rails.application.credentials.STAGING_DB_USERNAME %>
  password: <%= Rails.application.credentials.STAGING_DB_PASSWORD %>

production:
  <<: *default
  database: finally_production
  username: <%= Rails.application.credentials.PRODUCTION_DB_USERNAME %>
  password: <%= Rails.application.credentials.PRODUCTION_DB_PASSWORD %>

